# Author: Sebastian Dodt
# Date: 3 February 2023

# This application produces plots of illegal fishing data
# generated by Global Fishing Watch.

# Importing libraries from CRAN
library(shiny)
library(ggplot2)
library(DT)
library(shinyWidgets)
library(dplyr)
library(stringr)
library(tidyquant)
library(zoo)
library(tidyr)
library(countrycode)
library(devtools)
library(shinythemes)
library(shinyflags)


# Loading the UI
source("ui/run_ui.R")
ui <- run_ui()

# Load server function
source("server/run_server.R")

# Run application
shinyApp(
  ui = ui,
  server = server
)