# Author: Sebastian Dodt
# Date: 3 February 2023

# This application produces plots of illegal fishing data
# generated by Global Fishing Watch.

# Setting options
options(shiny.jquery.version=1)  # to get the tabs on the left side working.
# See https://github.com/MarkEdmondson1234/gentelellaShiny/issues/14

# Importing libraries from CRAN
library(shiny)
library(ggplot2)
library(DT)
library(shinyWidgets)
library(dplyr)
library(stringr)
library(tidyquant)
library(zoo)
library(tidyr)
library(countrycode)
library(devtools)

# Importing libraries from GitHub
# to install package, run the following line
# devtools::install_github("MarkEdmondson1234/gentelellaShiny")
library(gentelellaShiny)
# to install package, run the following line
# devtools::install_github("tutuchan/shinyflags")
library(shinyflags)


# Loading the UI
source("ui/run_ui.R")
ui <- run_ui()

# Load server function
source("server/run_server.R")

# Run application
shinyApp(
  ui = ui,
  server = server
)